require("core.config.tokyonight")
require("core.config.lualine")
require("core.config.nvim-tree")
require("core.config.treesitter")
require("core.config.telescope")
require("core.config.autopairs")
require("core.config.lsp-config")
require("core.config.nvterm")
require("core.config.vim-visual-multi")

